### ISSUE TITLE
[UI Components] Type definitions of utils shouldn't be included in dist

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/ui#16]
## Describe the bug

In `ui-components`, we have utils that help generate a new component from a boilerplate. I found that the type definitions of those utils are emitted and included in `dist` while they shouldn't be.

<img width="420" alt="Screenshot 2023-12-20 at 12 09 44" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/2a6dde02-07f7-49f5-ab3e-a8df428b459c">

## Expected behavior

The utils should still be type-checked but their type definitions shouldn't be emitted and included in `dist`.

**Comment by Nirajn2311** [comment]
> The build command creates a types folder, which we don't need.

I'd cleaned up the TS config to handle this but dint include it in yesterdays PR as it was out of scope. I'll update that change to prevent compiling utils type to `dist` also and open a PR in a hour or two.
