### ISSUE TITLE
Dropdown should have a top margin of 0.5px

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/ui#163]
## Description

The `Button` component has a top margin of 0.5px while `Dropdown` doesn't. When Button and Dropdown are used together:
- On desktop, there is a slight difference in the spacing
- On mobile, there is a slight misalignment

| Desktop | Mobile |
| --- | --- |
| <img width="1138" alt="Screenshot 2024-05-31 at 15 35 47" src="https://github.com/freeCodeCamp/ui/assets/25715018/2320200f-60c2-4b3d-b9f0-0ff1e9a9440f"> | <img width="900" alt="Screenshot 2024-05-31 at 15 41 19" src="https://github.com/freeCodeCamp/ui/assets/25715018/69f08793-ecd8-4c4c-9d71-7eef9f31ecbe"> |

Page tested: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code

## Changes needed

To address the issue, I think `Dropdown` should have a 0.5px top margin.

Though we might want to revisit this in the future, `Button` or `Dropdown` probably shouldn't have any margin, and their parent should be responsible for the layout (ref #13).

**Comment by a2937** [comment]
Excuse me, I have a silly question. How do I test my solution?

**Comment by a2937** [comment]
![Console screenshot](https://github.com/freeCodeCamp/ui/assets/9373245/a59af5b8-3236-4147-aa5c-e3c3e8f0811e)

I don't seem to have everything I need installed to run Storybook though. Where can I get it?

**Comment by a2937** [comment]
I didn't see those addons listed in package.json directly either, but it's fairly probably that it must have been bundled with something else.
