### ISSUE TITLE
[QuizQuestion] Render answer feedback

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/ui#331]
## Description

In challenges with multiple choice questions, we want to display the correct/incorrect icon within the selected answer with some hint text.

```
[ ] Option 1
[ ] Option 2
[x] Option 3
    x Incorrect. Some explanation...
[ ] Option 4
```

---

Currently we are displaying the icon next to the question text. I'll experiment a bit to see if we need that icon, or we can just rely on the answer feedback mentioned above.

**Comment by Prateek-Fst** [comment]
Hi, I was trying to work on this  issue I want  to get clarification whether the
e icon should be displayed  for the particular option(which we have currently selected )   like I have done in the screenshot below or we have to display the respected icon for  each option .
<img width="1680" alt="Screenshot 2024-09-24 at 8 58 44 PM" src="https://github.com/user-attachments/assets/aad4b928-edd8-4126-9073-28b18018c275">

**Comment by Prateek-Fst** [comment]
Sure Thanks for the information!!!!
