### ISSUE TITLE
[Container] Correct the text color of `p` on Storybook demo

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/ui#392]
## Description

The text on the [Storybook page of the Container component](https://opensource.freecodecamp.org/ui/?path=/story/components-container--default&globals=backgrounds.value:!hex(1b1b32)) is not having the correct color.

<details>
  <summary>Screenshot</summary>

  ![Image](https://github.com/user-attachments/assets/2485da7d-5869-4adb-97b2-10e3c46438e2)
</details>

To fix this, add the `text-foreground-primary` class to each `p`:

https://github.com/freeCodeCamp/ui/blob/9a27b8f4226695951d79a5f334b13c2af3925695/src/container/container.stories.tsx#L20-L31

## Note 

Do not add this rule to any CSS file. This will cause styling issues in the /learn client.

**Comment by shootermv** [comment]
what is the reason for multiple p tags?
