### ISSUE TITLE
[UI Components] Add Storybook smoke test to CI

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/ui#9]
### Is your feature request related to a problem? Please describe.

Prevent https://github.com/freeCodeCamp/freeCodeCamp/issues/46584 from happening again by adding smoke test to our CI.

We can look at the `--smoke-test` flag from Storybook or the [test-runner addon](https://github.com/storybookjs/test-runner).

**Comment by ojeytonwilliams** [comment]
@huyenltnguyen Was this resolved by https://github.com/freeCodeCamp/ui/pull/22?
